# Generated by Django 4.2.1 on 2023-07-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_currency'),
        ('products', '0003_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currnecy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='curr_product', to='category.currency'),
            preserve_default=False,
        ),
    ]
