# Generated by Django 4.2.1 on 2023-07-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_currnecy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currnecy',
            new_name='currency',
        ),
    ]
