# Generated by Django 4.2.1 on 2023-08-11 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_resetpasscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasscode',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resetpasscode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpasscode',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
