# Generated by Django 4.2.1 on 2023-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardads',
            options={'verbose_name': 'Карточка реклама', 'verbose_name_plural': 'Карточка реклама'},
        ),
        migrations.AlterModelOptions(
            name='sliderads',
            options={'verbose_name': 'Слайдер реклама', 'verbose_name_plural': 'Слайдер реклама'},
        ),
        migrations.AddField(
            model_name='cardads',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderads',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
